# Generated by Django 3.0.8 on 2020-12-06 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UsuNom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
                ('UsuSex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True, verbose_name='Sexo del trabajador')),
                ('UsuFecNac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('UsuDNI', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='DNI')),
                ('UsuTel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de contacto')),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
