# Generated by Django 3.0.8 on 2020-12-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0001_initial'),
        ('presentaciones', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida_Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalDetCosUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('SalDetCan', models.IntegerField(verbose_name='Cantidad')),
                ('SalDetArtCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulo', verbose_name='Artículo')),
                ('SalDetCabCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salidas.Salida_Cabecera', verbose_name='Número de factura')),
                ('SalDetPreCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentaciones.Presentacion', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name_plural': 'Detalles de salida de productos',
                'unique_together': {('SalDetCabCod', 'SalDetArtCod')},
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='ArtSalDet',
            field=models.ManyToManyField(through='articulos.Salida_Detalle', to='salidas.Salida_Cabecera'),
        ),
    ]
